[schedule]
frequency = "10 seconds"
samples = 4

[[sources]]
type = "timestamp"
id = "timestamp"

    [sources.config]
    epochf = true
    iso8601 = true
    strftime = "%Y-%m-%d %H:%M:%S"

[[sources]]
type = "git"
id = "git"

    [sources.config]
    directory = "{git.root}"

[[sources]]
type = "my_source"
id = "my_source"

[[sources]]
type = "user"
id = "user"

[[sources]]
type = "env"
id = "env"

    [sources.config]
    include = ["LANG"]
    exclude = []
    lowercase = false

[[sources]]
type = "env"
id = "env_lower"

    [sources.config]
    include = ["PYTHONHASHSEED"]
    exclude = []
    lowercase = true

[[sources]]
type = "cobertura"
id = "coverage"

    [sources.config]
    xmlpath = "{pipeline.dir}/coverage.xml"

[[sinks]]
type = "print"
id = "print"

[[sinks]]
type = "archive"
id = "archive"

    [sinks.config]
    output = "data.json"
    override = true
    create_parents = true

[[sinks]]
type = "template"
id = "template1"

    [sinks.config]
    template = "file://{pipeline.dir}/template.tpl"
    output = "render1.html"
    override = true
    create_parents = true

[[sinks]]
type = "template"
id = "template2"

    [sinks.config]
    template = "python://flowconf:get_template"
    output = "render2.html"
    override = true
    create_parents = true

[[sinks]]
type = "mongodb"
id = "mongodb"

    [sinks.config]
    uri = "mongodb://localhost:27017/"
    database = "flowbber"
    collection = "pipeline1data"

[[sinks]]
type = "influxdb"
id = "influxdb"

    [sinks.config]
    uri = "influxdb://localhost:8086/"
    database = "flowbber"
    key = "timestamp.iso8601"
